[server]
address = "0.0.0.0"  # Set the server address (e.g., "0.0.0.0" for public access)
port = 8501  # Set the desired port (default is 8501)
enableCORS = false  # Optional: Disable CORS if you don't need it
